apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-nginx
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: nginx-helm
    repoURL: "https://github.com/NirupamDebnath/argocd-demo.git"
    targetRevision: main
    helm:
      releaseName: argocd-helm-release
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
