{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx-helm.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ $fullName }}-gateway
  http:
    - match:
        - uri:
            prefix: /{{ .Values.image.repository }}/
        - uri:
            exact: /{{ .Values.image.repository }}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ $svcPort }}
              
{{- end }}
