apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    service: elasticsearch
spec:
  ports:
    - port: 9200
      name: http
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      version: v1
  template:
    metadata:
      labels:
        app: elasticsearch
        version: v1
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
          securityContext:
            runAsUser: 1000
